/**
 * 英文
 */
export default {
  frame: {
    themeSetting: 'Theme Settings',
    themeMode: 'Light/Dark',
    setting: 'Settings',
    theme: 'Theme',
    message: 'Message',
    selectTheme: 'Select Theme',
    colorPrimary: 'Primary Color',
    colorError: 'Error Color',
    colorWarning: 'Warning Color',
    colorSuccess: 'Success Color',
    colorInfo: 'Link Color',
    componentSize: 'Component Size',
    menuLayout: 'Menu Layout',
    formLayout: 'Form Layout',
    horizontal: 'horizontal',
    vertical: 'vertical',
    inline: 'inline',
    small: 'Small',
    middle: 'Medium',
    large: 'Large',
    dark: 'Dark Mode',
    modeAnimateFade: 'Fade In/Out',
    modeAnimateCircle: 'Circle Clip',
    modeAnimate: 'Mode Animation',
    radiusLayout: 'Rounded Layout',
    useTabs: 'Use Tabs Page',
    tabAnimate: 'Tab Page Animation',
    tabAnimateNone: 'None',
    tabAnimateSlideRight: 'Slide Right',
    tabAnimateFade: 'Fade In/Out',
    tabAnimateScale: 'Scale',
    useDynamicPageTitle: 'Dynamic Page Title',
    lang: 'Language',
    selectLang: 'Select Language',
    other: 'Other',
    showWeather: 'Show Weather',
    personalCenter: 'Personal Center',
    logout: 'Log Out',
    notLogin: 'Not Logged In',
    fullscreen: 'Fullscreen',
    exitFullscreen: 'Exit Fullscreen',
    closeLeft: 'Close Left',
    closeRight: 'Close Right',
    closeOther: 'Close Others',
    top: 'Top',
    left: 'Left',
    topLeft: 'TopLeft',
    useTableBorder: 'Use Table Border',
    useBreadcrumbs: 'Use Breadcrumbs',
  },
  // crud
  crud: {
    add: 'Add',
    batchDelete: 'Batch Delete',
    export: 'Export',
    back: 'Back',
    search: 'Search',
    reset: 'Reset',
    rememberSearch: 'Remember Search',
    notLog: 'No History',
    pleaseEnterRemark: 'Please enter remarks',
    pleaseEnterSearchParams: 'Please fill in search criteria first',
    submit: 'Submit',
    cancel: 'Cancel',
    notNull: '{label} cannot be empty',
    someRowNotNull: 'Row {rowNum} [{label}] cannot be empty',
    clickToDownload: 'Click to download',
    importTemplate: 'Import Template',
    dragFileToUpload: 'Drag file here or click to upload',
    pleaseUploadExcel: 'Please upload .xls, .xlsx files',
    sameDataIsReplace: 'Overwrite duplicate records?',
    import: 'Import',
    importSuccess: 'Import successful',
    yes: 'Yes',
    no: 'No',
    edit: 'Edit',
    detail: 'Detail',
    close: 'Close',
    delete: 'Delete',
    deleteSuccess: 'Deleted successfully',
    toggleSuccess: 'Status toggled successfully',
    warmTips: 'Tips',
    confirmDeleteBySelected: 'Are you sure you want to delete selected items ({value} items)?',
    addSuccess: 'Added successfully',
    updateSuccess: 'Updated successfully',
    pleaseEnter: 'Please enter {text}',
    pleaseSelect: 'Please select {text}',
    pleaseSelectStart: 'Select start {text}',
    pleaseSelectEnd: 'Select end {text}',
    pleaseEnterOrSelect: 'Please enter or select {text}',
    start: 'Start',
    end: 'End',
    all: 'All',
    refreshSuccess: 'Refreshed successfully',
    refreshData: 'Refresh Data',
    confirmDoIt: 'Are you sure to perform {text} operation on this record?',
    this: 'This',
    more: 'More',
    count: 'Total',
    pleaseEnterKeywordToSearch: 'Please enter keyword to search',
  }
}