/**
 * 中文简体
 */
export default {
  // 框架
  frame: {
    themeSetting: '主题设置',
    setting: '设置',
    theme: '主题',
    selectTheme: '选择主题',
    componentSize: '组件大小',
    menuLayout: '菜单布局',
    formLayout: '表单布局',
    horizontal: 'horizontal',
    vertical: 'vertical',
    inline: 'inline',
    small: '小',
    middle: '中',
    large: '大',
    dark: '暗色模式',
    radiusLayout: '圆润布局',
    useTabs: '使用标签页',
    useDynamicPageTitle: '动态网页标题',
    lang: '语言',
    selectLang: '选择语言',
    other: '其他',
    showWeather: '展示天气',
    personalCenter: '个人中心',
    logout: '退出系统',
    notLogin: '未登录',
    fullscreen: '全屏',
    exitFullscreen: '退出全屏',
    closeLeft: '关闭左侧',
    closeRight: '关闭右侧',
    closeOther: '关闭其他',
    top: '顶部',
    left: '左侧',
    topLeft: '混合',
  },
  // crud
  crud: {
    add: '新增',
    batchDelete: '批量删除',
    export: '导出',
    back: '返回',
    search: '查询',
    reset: '重置',
    rememberSearch: '记住查询',
    notLog: '暂无历史记录',
    pleaseEnterRemark: '请输入备注',
    pleaseEnterSearchParams: '请先填写查询条件',
    submit: '提交',
    cancel: '取消',
    notNull: '{label}不能为空',
    someRowNotNull: '第 {rowNum} 行[{label}]不能为空',
    clickToDownload: '点击此处下载',
    importTemplate: '导入模板',
    dragFileToUpload: '将文件拖到此处，或点击上传',
    pleaseUploadExcel: '请上传 .xls, .xlsx 文件',
    sameDataIsReplace: '重复记录是否覆盖更新',
    import: '导入',
    importSuccess: '导入成功',
    yes: '是',
    no: '否',
  },
}