export default {
  system: {
    dict: {
      "type": "Type",
      "enName": 'En Name',
      "typePlaceholder": "Please enter type",
      "name": "Name",
      "namePlaceholder": "Please enter name",
      "id": "ID",
      "remark": "Remark",
      "isEnabled": "Enabled",
      "createTime": "Creation Time",
      "operation": "Operation",
      "manageItems": "Dictionary Items Management",
      "disable": "Disable",
      "enable": "Enable",
      "edit": "Edit",
      "detail": "Details",
      "delete": "Delete",
      "dictType": "Dictionary Type",
      "confirmEdit": "Confirm Edit",
      "confirmSubmit": "Confirm Submit",
      "typeTooltip": "Dictionary type must start with a letter and can only contain (lowercase letters, numbers, underscore)",
      "dictItemListTitle": "Dictionary 【{name}】 Item List",
      "code": "Code",
      "sort": "Sort",
      "value": "Dictionary Value",
      "deleteConfirm": "Deleting dictionary may affect business data display, confirm deletion?",
      "dictData": "Dictionary Data",
      "confirmSubmitContinue": "Confirm and Continue",
      "tagType": "Tag Type",
      "tagTypeDefault": "Default",
      "tagTypeProcessing": "Processing",
      "tagTypeSuccess": "Success",
      "tagTypeWarning": "Warning",
      "tagTypeError": "Error",
      "tagTypeGold": "Gold",
      "tagTypePurple": "Purple",
      "tagTypeCyan": "Cyan",
      "tagTypeRed": "Red",
      "tagTypeBlue": "Blue",
      "tagTypePink": "Pink",
      "tagTypeRedInverse": "Red Inverse",
      "tagTypeBlueInverse": "Blue Inverse",
      "tagTypeGreenInverse": "Green Inverse",
      "tagTypeOrangeInverse": "Orange Inverse",
      "tagTypeGrayInverse": "Gray Inverse",
      "cssClass": "Additional CSS Class"
    }
  }
}