/**
 * ant-design-vue 4.x 图标组件 a-icon 实现
 * <a-icon type="PlusOutlined" />
 */
import { createVNode } from 'vue'
import {
  VerticalAlignBottomOutlined, RollbackOutlined, RetweetOutlined, SwapOutlined, LoginOutlined,
  LogoutOutlined, PlayCircleOutlined, ClockCircleOutlined, WarningOutlined, AreaChartOutlined,
  PieChartOutlined, BarChartOutlined, DotChartOutlined, LineChartOutlined, RadarChartOutlined,
  HeatMapOutlined, FundOutlined, AndroidOutlined, AppleOutlined, WindowsOutlined, WechatOutlined,
  AlipayCircleOutlined, AlipayOutlined, AccountBookOutlined, AimOutlined, AlertOutlined,
  ApartmentOutlined, ApiOutlined, AppstoreAddOutlined, AppstoreOutlined, AudioOutlined,
  AudioMutedOutlined, AuditOutlined, BankOutlined, BarcodeOutlined, BarsOutlined, BellOutlined,
  BlockOutlined, BookOutlined, BorderOutlined, BorderlessTableOutlined, BranchesOutlined, BugOutlined,
  BuildOutlined, BulbOutlined, CalculatorOutlined, CalendarOutlined, CameraOutlined, CarOutlined,
  CarryOutOutlined, CiCircleOutlined, CiOutlined, ClearOutlined, EditOutlined,
  CloudDownloadOutlined, CloudOutlined, CloudServerOutlined, CloudSyncOutlined, CloudUploadOutlined,
  ClusterOutlined, CodeOutlined, CoffeeOutlined, CommentOutlined, CompassOutlined, ConsoleSqlOutlined,
  ContactsOutlined, ContainerOutlined, ControlOutlined, CopyrightOutlined, CreditCardOutlined,
  CrownOutlined, CustomerServiceOutlined, DashboardOutlined, DatabaseOutlined, DeliveredProcedureOutlined,
  DeploymentUnitOutlined, DesktopOutlined, DisconnectOutlined, DislikeOutlined, DollarOutlined,
  DownloadOutlined, EnvironmentOutlined, EuroOutlined, ExceptionOutlined, ExperimentOutlined,
  ExportOutlined, FieldTimeOutlined, FileAddOutlined, FileDoneOutlined, FileOutlined, FileProtectOutlined,
  FileSearchOutlined, FileSyncOutlined, FileTextOutlined, FileUnknownOutlined, FileWordOutlined,
  FileZipOutlined, FilterOutlined, FireOutlined, FlagOutlined, FolderAddOutlined, FolderOutlined,
  FolderOpenOutlined, FolderViewOutlined, ForkOutlined, FormatPainterOutlined, FrownOutlined,
  FunctionOutlined, FundProjectionScreenOutlined, FundViewOutlined, FunnelPlotOutlined, GatewayOutlined,
  GifOutlined, GiftOutlined, GlobalOutlined, GoldOutlined, GroupOutlined, HddOutlined, HeartOutlined,
  HistoryOutlined, HolderOutlined, HomeOutlined, HourglassOutlined, IdcardOutlined, ImportOutlined,
  InboxOutlined, InsuranceOutlined, InteractionOutlined, KeyOutlined, LaptopOutlined, LayoutOutlined,
  LikeOutlined, LinkOutlined, LockOutlined, MacCommandOutlined, MailOutlined, ManOutlined,
  MedicineBoxOutlined, MehOutlined, MenuOutlined, MergeCellsOutlined, MessageOutlined, MobileOutlined,
  MoneyCollectOutlined, NodeIndexOutlined, NotificationOutlined, NumberOutlined, OneToOneOutlined,
  PaperClipOutlined, PartitionOutlined, PayCircleOutlined, PercentageOutlined, PhoneOutlined,
  PictureOutlined, PlaySquareOutlined, PoundCircleOutlined, PoundOutlined, PoweroffOutlined,
  PrinterOutlined, ProfileOutlined, ProjectOutlined, PropertySafetyOutlined, PullRequestOutlined,
  PushpinOutlined, QrcodeOutlined, ReadOutlined, ReconciliationOutlined, RedEnvelopeOutlined,
  ReloadOutlined, RestOutlined, RobotOutlined, RocketOutlined, RotateLeftOutlined, RotateRightOutlined,
  SafetyCertificateOutlined, SafetyOutlined, SaveOutlined, ScanOutlined, ScheduleOutlined,
  SearchOutlined, SecurityScanOutlined, SelectOutlined, SendOutlined, SettingOutlined, ShakeOutlined,
  ShareAltOutlined, ShopOutlined, ShoppingCartOutlined, ShoppingOutlined, SisternodeOutlined,
  SkinOutlined, SmileOutlined, SolutionOutlined, SoundOutlined, SplitCellsOutlined, StarOutlined,
  SubnodeOutlined, SwitcherOutlined, SyncOutlined, TableOutlined, TabletOutlined, TagOutlined,
  TagsOutlined, TeamOutlined, ThunderboltOutlined, ToTopOutlined, ToolOutlined,
  TrademarkOutlined, TransactionOutlined, TranslationOutlined, TrophyOutlined, UngroupOutlined,
  UnlockOutlined, UploadOutlined, UsbOutlined, UserAddOutlined, UserDeleteOutlined, UserOutlined,
  UserSwitchOutlined, UsergroupAddOutlined, UsergroupDeleteOutlined, VerifiedOutlined,
  VideoCameraAddOutlined, VideoCameraOutlined, WalletOutlined, WhatsAppOutlined, WifiOutlined,
  WomanOutlined, ClockCircleFilled, WarningFilled, FundFilled, PieChartFilled, AndroidFilled,
  AppleFilled, WindowsFilled, AlipaySquareFilled, AppstoreFilled, BankFilled,
  BellFilled, BookFilled, BugFilled, CalculatorFilled, CalendarFilled, CameraFilled, CarFilled,
  CloudFilled, CodeFilled, CodeSandboxSquareFilled, DollarCircleFilled, FlagFilled, FileFilled,
  GiftFilled, GoldFilled, HeartFilled, HomeFilled, IdcardFilled, InsuranceFilled, PayCircleFilled,
  PhoneFilled, PictureFilled, PrinterFilled, ProfileFilled, PropertySafetyFilled,
  SafetyCertificateFilled, SettingFilled, ShopFilled, ShoppingFilled, SignalFilled, SkinFilled,
  SoundFilled, StarFilled, TagFilled, TagsFilled, WalletFilled
} from '@ant-design/icons-vue'

export const icons = {
  VerticalAlignBottomOutlined, RollbackOutlined, RetweetOutlined, SwapOutlined, LoginOutlined,
  LogoutOutlined, PlayCircleOutlined, ClockCircleOutlined, WarningOutlined, AreaChartOutlined,
  PieChartOutlined, BarChartOutlined, DotChartOutlined, LineChartOutlined, RadarChartOutlined,
  HeatMapOutlined, FundOutlined, AndroidOutlined, AppleOutlined, WindowsOutlined, WechatOutlined,
  AlipayCircleOutlined, AlipayOutlined, AccountBookOutlined, AimOutlined, AlertOutlined,
  ApartmentOutlined, ApiOutlined, AppstoreAddOutlined, AppstoreOutlined, AudioOutlined,
  AudioMutedOutlined, AuditOutlined, BankOutlined, BarcodeOutlined, BarsOutlined, BellOutlined,
  BlockOutlined, BookOutlined, BorderOutlined, BorderlessTableOutlined, BranchesOutlined, BugOutlined,
  BuildOutlined, BulbOutlined, CalculatorOutlined, CalendarOutlined, CameraOutlined, CarOutlined,
  CarryOutOutlined, CiCircleOutlined, CiOutlined, ClearOutlined, EditOutlined,
  CloudDownloadOutlined, CloudOutlined, CloudServerOutlined, CloudSyncOutlined, CloudUploadOutlined,
  ClusterOutlined, CodeOutlined, CoffeeOutlined, CommentOutlined, CompassOutlined, ConsoleSqlOutlined,
  ContactsOutlined, ContainerOutlined, ControlOutlined, CopyrightOutlined, CreditCardOutlined,
  CrownOutlined, CustomerServiceOutlined, DashboardOutlined, DatabaseOutlined, DeliveredProcedureOutlined,
  DeploymentUnitOutlined, DesktopOutlined, DisconnectOutlined, DislikeOutlined, DollarOutlined,
  DownloadOutlined, EnvironmentOutlined, EuroOutlined, ExceptionOutlined, ExperimentOutlined,
  ExportOutlined, FieldTimeOutlined, FileAddOutlined, FileDoneOutlined, FileOutlined, FileProtectOutlined,
  FileSearchOutlined, FileSyncOutlined, FileTextOutlined, FileUnknownOutlined, FileWordOutlined,
  FileZipOutlined, FilterOutlined, FireOutlined, FlagOutlined, FolderAddOutlined, FolderOutlined,
  FolderOpenOutlined, FolderViewOutlined, ForkOutlined, FormatPainterOutlined, FrownOutlined,
  FunctionOutlined, FundProjectionScreenOutlined, FundViewOutlined, FunnelPlotOutlined, GatewayOutlined,
  GifOutlined, GiftOutlined, GlobalOutlined, GoldOutlined, GroupOutlined, HddOutlined, HeartOutlined,
  HistoryOutlined, HolderOutlined, HomeOutlined, HourglassOutlined, IdcardOutlined, ImportOutlined,
  InboxOutlined, InsuranceOutlined, InteractionOutlined, KeyOutlined, LaptopOutlined, LayoutOutlined,
  LikeOutlined, LinkOutlined, LockOutlined, MacCommandOutlined, MailOutlined, ManOutlined,
  MedicineBoxOutlined, MehOutlined, MenuOutlined, MergeCellsOutlined, MessageOutlined, MobileOutlined,
  MoneyCollectOutlined, NodeIndexOutlined, NotificationOutlined, NumberOutlined, OneToOneOutlined,
  PaperClipOutlined, PartitionOutlined, PayCircleOutlined, PercentageOutlined, PhoneOutlined,
  PictureOutlined, PlaySquareOutlined, PoundCircleOutlined, PoundOutlined, PoweroffOutlined,
  PrinterOutlined, ProfileOutlined, ProjectOutlined, PropertySafetyOutlined, PullRequestOutlined,
  PushpinOutlined, QrcodeOutlined, ReadOutlined, ReconciliationOutlined, RedEnvelopeOutlined,
  ReloadOutlined, RestOutlined, RobotOutlined, RocketOutlined, RotateLeftOutlined, RotateRightOutlined,
  SafetyCertificateOutlined, SafetyOutlined, SaveOutlined, ScanOutlined, ScheduleOutlined,
  SearchOutlined, SecurityScanOutlined, SelectOutlined, SendOutlined, SettingOutlined, ShakeOutlined,
  ShareAltOutlined, ShopOutlined, ShoppingCartOutlined, ShoppingOutlined, SisternodeOutlined,
  SkinOutlined, SmileOutlined, SolutionOutlined, SoundOutlined, SplitCellsOutlined, StarOutlined,
  SubnodeOutlined, SwitcherOutlined, SyncOutlined, TableOutlined, TabletOutlined, TagOutlined,
  TagsOutlined, TeamOutlined, ThunderboltOutlined, ToTopOutlined, ToolOutlined,
  TrademarkOutlined, TransactionOutlined, TranslationOutlined, TrophyOutlined, UngroupOutlined,
  UnlockOutlined, UploadOutlined, UsbOutlined, UserAddOutlined, UserDeleteOutlined, UserOutlined,
  UserSwitchOutlined, UsergroupAddOutlined, UsergroupDeleteOutlined, VerifiedOutlined,
  VideoCameraAddOutlined, VideoCameraOutlined, WalletOutlined, WhatsAppOutlined, WifiOutlined,
  WomanOutlined, ClockCircleFilled, WarningFilled, FundFilled, PieChartFilled, AndroidFilled,
  AppleFilled, WindowsFilled, AlipaySquareFilled, AppstoreFilled, BankFilled,
  BellFilled, BookFilled, BugFilled, CalculatorFilled, CalendarFilled, CameraFilled, CarFilled,
  CloudFilled, CodeFilled, CodeSandboxSquareFilled, DollarCircleFilled, FlagFilled, FileFilled,
  GiftFilled, GoldFilled, HeartFilled, HomeFilled, IdcardFilled, InsuranceFilled, PayCircleFilled,
  PhoneFilled, PictureFilled, PrinterFilled, ProfileFilled, PropertySafetyFilled,
  SafetyCertificateFilled, SettingFilled, ShopFilled, ShoppingFilled, SignalFilled, SkinFilled,
  SoundFilled, StarFilled, TagFilled, TagsFilled, WalletFilled
}

const AIcon = function ({ type }) {
  return (type && icons[type] && createVNode(icons[type])) ?? ''
}

export { AIcon }
